F/ws check
zetane/ZetaForge pull request #107
Opened 2024-06-14 19:34 UTC by jmagoon

- Adds tabs
- Adds history of pipelines
- Adds columns to the db for storing argo execution ids
- Adds results to the database instead of storing in s3
- Adds loading previous pipeline runs
- Adds new pipelines runs from previous runs
- Allows swapping between pipelines
- Allows stopping runs
- Changes how logs work to store them persistently and retrieve them per pipeline
- Adds new response types for pipelines + executions
- Adds minor fixes in electron (cachePath)

2024-06-17 15:01 UTC, plparent requested changes

2024-06-18 16:26 UTC, jmagoon commented on executor.go
> +			fmt.Printf(".")
log.Printf will write to console, websocket, and logfile. fmt will only write to console

2024-06-18 17:01 UTC, FGRCL approved these changes

2024-06-18 17:35 UTC, jmagoon commented on frontend/electron/preload/index.ts
> +  local: path.join(process.cwd(), ".cache") + path.sep,
Yes

2024-06-18 17:36 UTC, jmagoon commented on frontend/src/utils/sha1.js
> +/*
I used a library, I can remove this file

2024-06-18 17:39 UTC, jmagoon commented on frontend/electron/preload/index.ts
> +  local: path.join(process.cwd(), ".cache") + path.sep,
`window.cache.local`

2024-06-18 17:44 UTC, jmagoon commented on frontend/server/pipelineSerialization.js
> +          const fileName = param.value.split("/").at(-1)
i'm using `blob` to indicate it's in s3, not coming from disk

2024-06-18 17:48 UTC, jmagoon commented on frontend/server/s3.js
> +    const source = encodeURI(`/${config.s3.bucket}/${copyKey}`)
Only this arg requires uri encoding (per their docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/command/CopyObjectCommand/)

2024-06-18 17:49 UTC, jmagoon commented on frontend/server/s3.js
> +export async function getFileData(key, anvilConfiguration) {
I have these in the client version, would like to keep them for when we will need them

2024-06-18 17:49 UTC, jmagoon commented on frontend/server/s3.js
> +export async function getFile(key, destinationPath) {
Will be used for syncing from s3 -> local disk

2024-06-18 17:54 UTC, jmagoon commented on frontend/server2/entrypoint.py
> +#            shutil.move(src_path, dst_path)
I would like to keep it, in case we notice a slowdown in copy performance

2024-06-18 17:56 UTC, jmagoon commented on frontend/src/atoms/pipelineAtom.js
> +    defaultPipeline = Object.assign(defaultPipeline, pipeline)
It builds a default pipeline and then if there's any other properties coming in the constructor it overrides the defaults from the factor

2024-06-18 17:58 UTC, jmagoon commented on frontend/src/components/ProviderInjector.jsx
> +const queryClient = new QueryClient({
It's right below:
```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      networkMode: 'offlineFirst'
    },
    mutations: {
      networkMode: 'offlineFirst'
    }
  }
})

export default function ProviderInjector({ children }) {
  return (
    <trpc.Provider client={trpcClient} queryClient={queryClient}>
      <QueryClientProvider client={queryClient}>
        {children}
      </QueryClientProvider>
    </trpc.Provider>
  )
}```

2024-06-18 18:00 UTC, jmagoon commented on frontend/src/components/ZetaneDrawflowEditor.js
> +
When I tried, `.difference` was not supported in Electron

2024-06-18 18:01 UTC, jmagoon commented on frontend/src/components/ZetaneDrawflowEditor.js
> +
So this is using object keys

2024-06-18 18:03 UTC, jmagoon commented on frontend/src/atoms/pipelineAtom.js
> +}
Good idea, I'll address it in another MR as right now it's doing functionally the same thing:
```
  useEffect(() => {
    const runs = getPipelines(workspace)
    setExecutions(runs)
  }, [workspace?.pipelines])```

2024-06-18 18:04 UTC, merged